### ISSUE TITLE
ImportError: libcudart.so.12

### ISSUE THREAD

**Issue by niknoproblems** [Troyanovsky/Local-LLM-Comparison-Colab-UI#10]
when I tried to run Mistral-7B-OpenOrca (using oobabooga/text-generation-webui)Ж
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

**Comment by niknoproblems** [comment]
It was solved when I commented out these lines:
!pip uninstall flash-attn
!pip install --no-build-isolation flash-attn==2.3.0

**Comment by gleitz** [comment]
You can also roll forward to version 2.3.3.

```
!pip uninstall flash-attn
!pip install --no-build-isolation flash-attn==2.3.3
````
